### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'glActiveTexture'

### ISSUE THREAD

**Issue by retikulumx** [adafruit/Raspberry-Pi-Installer-Scripts#226]
On a Raspberry Zero, fresh installed, I get the following error

`Traceback (most recent call last):
  File "/boot/Pi_Eyes/eyes.py", line 9, in <module>
    import pi3d
  File "/usr/local/lib/python3.9/dist-packages/pi3d/__init__.py", line 10, in <module>
    from pi3d.constants import (USE_PYGAME, PIL_OK,
  File "/usr/local/lib/python3.9/dist-packages/pi3d/constants/__init__.py", line 198, in <module>
    PLATFORM, bcm, openegl, opengles = _detect_platform_and_load_libraries()
  File "/usr/local/lib/python3.9/dist-packages/pi3d/constants/__init__.py", line 193, in _detect_platform_and_load_libraries
    set_gles_function_args(opengles) #function defined in constants/gl.py
  File "/usr/local/lib/python3.9/dist-packages/pi3d/constants/gl.py", line 387, in set_gles_function_args
    gles.glActiveTexture.argtypes = [GLenum] #
AttributeError: 'NoneType' object has no attribute 'glActiveTexture'`

**Comment by MNTrailBoss** [comment]
Ditto.    Right after reboot from the pieyes load.

**Comment by PaintYourDragon** [comment]
From the forums, somewhat different hardware but same error, unsure of fix but something to try:

> Not sure what to suggest here. Just tested with 2022-09-22-raspios-buster-armhf-lite.img.xz, ran pi-eyes.sh for 240x240 screens, reboot when prompted and it runs successfully on both Pi 3 B and B+.
> 
> Just rampant speculation because I don’t know what else it could be, but if it’s a slower SD card, maybe some prerequisite service is taking some time to load. Try adding a delay (e.g. 10 seconds) in /etc/rc.local before eyes.py is run:
> `cd /boot/Pi_Eyes;sleep 10;python3 eyes.py --radius 240 &`

**Comment by bikerglen** [comment]
FWIW: With a RPi 3B+, the Adafruit Animated Eyes Bonnet (# 3813), and two of the Adafruit OLED displays (# 1431), I had to go all the way back to `2021-05-07-raspios-buster-armhf-lite.img` to get it to work. With a more recent OS, e.g. any `Bullseye` or `Bookworm` version, I had the same `AttributeError: 'NoneType' object has no attribute 'glActiveTexture'` error as the other users.

No problem, however, using the latest and greatest OS images with a RPi 4.

**Comment by retikulumx** [comment]
> No problem, however, using the latest and greatest OS images with a RPi 4.

You mean, on Rpi4 it runs with the most recent bookworm?

Yeah, my Zero with Pi-Eyes is also running on buster. It's a shame that the thing only runs with a Linux pre-pre-release. No further development. That has to be stated on the product pages and I would have liked to know this before buying the hardware.

**Comment by bikerglen** [comment]
> You mean, on Rpi4 it runs with the most recent bookworm?

Crud. Sorry. I mean the latest legacy 32-bit full version. "Raspberry Pi OS (Legacy) Full" and dated 2023-05-03 in the official Raspberry Pi Imager tool. I can grab another OLED and double check this later today.

The Adafruit Pi Eyes installer script has trouble with the mandatory Python venv's in Bookworm.

**Comment by PaintYourDragon** [comment]
Software dependencies are explained in the guide:
https://learn.adafruit.com/animated-snake-eyes-bonnet-for-raspberry-pi/software-installation
In short: **Desktop Bullseye** on Pi 4, **Lite Legacy** (Buster) on older boards, **32-bit** in all cases.
Haven’t yet tested w/Bookworm on any board (incl Pi 5).

Compatibility issues — the glActiveTexture message, etc. — are a product of the **Pi3D** library. That got all complicated with the release of the Pi 4 and is the reason different OS versions are needed in each case. A single-current-OS approach would be _really_ nice, but I don’t know if that’s ever coming to Pi3D or if broadly compatible alternatives exist (maybe vulkan, IDK).

**Comment by makermelissa-ai-assistant** [comment]
Closing as out-of-scope for this repo.

Per @PaintYourDragon's [earlier comment](https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/issues/226#issuecomment-1781421247), this is a [Pi3D](https://github.com/tipam/pi3d) library compatibility issue, not an installer-script bug — the `gles.glActiveTexture` failure happens during Pi3D's own platform detection, before any of the installer-provided code runs.

The fix path is upstream in Pi3D (or pinning OS versions per the guide). The installer script itself isn't broken.

For anyone landing here: the [Animated Snake Eyes guide](https://learn.adafruit.com/animated-snake-eyes-bonnet-for-raspberry-pi/software-installation) documents the supported OS combinations (Desktop Bullseye on Pi 4, Lite Legacy/Buster on older boards, 32-bit in all cases).

**Comment by makermelissa** [comment]
@makermelissa-piclaw, I'm going to keep this open for now. I'd like to do a rewrite that works for modern systems soon as a fix.

**Comment by makermelissa** [comment]
Fixed by #373
